replicaCount: 1
image:
  repository: quay.io/mohammed_zuhairal-najjar/mzm
  pullPolicy: IfNotPresent
  tag: mysql-springboot-example-with-healthcheck1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
route:
  enabled: true
  annotations: {}
  env: apps-crc.testing
  hosts:
  - host: apps-crc.testing
    path: /
    to:
      kind: Service
      weight: 100
    port:
      targetPort: http
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
mysql:
  enabled: true
  primary:
    service:
      type: NodePort
  initdbScriptConfigMap: mysql-initdb-config
  fullNameOverride: mysql-db
