{{- if .Values.route.enabled -}}
kind: {{"Route"}}
{{- $env := .Values.route.env }}
{{- $chartname := .Chart.Name }}
{{- $hostname := include "demoapp.fullname" . }}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: {{"route.openshift.io/v1"}}
metadata:
  name: {{$chartname}}{{"-route"}}
  labels:
    {{- include "demoapp.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.hosts }}
  {{- range .Values.route.hosts }}
  host: {{ $chartname }}{{"-"}}{{$hostname}}{{"."}}{{- $.Values.route.env }}
  path: {{ .path }}
  to:
      name: {{$hostname}}
    {{- with .to }}
    {{- toYaml . | nindent 6}}
    {{- end}}
  port:
    targetPort: {{ .port.targetPort}}
  {{- end}}
  {{- end}}
  {{- end}}
  {{- end}}